	<form<?php echo $this->render('forms/partials/form_attributes.phtml'); ?>>
		<?php
		$aErrors = $this->element->getErrors();
		Zend_Debug::dump($aErrors, 'Errors in Form');
		$aMessages = $this->element->getErrorMessages();
		Zend_Debug::dump($aMessages, 'Error Messages in Form');
		?>
        <?php echo $this->element->textEmail->getLabel() . ' ' . $this->element->textEmail; ?> <br />
		<?php echo $this->element->textSomething->getLabel() . ' ' . $this->element->textSomething; ?> <br />
        <?php echo $this->element->submitSubmit; ?>
		<?php echo $this->element->csrf_hash; ?>
	</form>

