<div class="row">

	<div class="span3 cDivPaginationPageOfPage">Page <?php echo $this->current; ?> of <?php echo $this->last; ?>.</div>

	<div class="span9">
		<div class="pagination pagination-right">
			<ul>

<?php if (isset($this->previous)): ?>
				<li>
					<a href="<?php echo $this->url(array('page' => $this->first)); ?>"><i class="icon-fast-backward" title="First"></i></a>
				</li>
<?php else: ?>
				<li class="disabled">
					<a href=""><i class="icon-fast-backward" title="First"></i></a>
				</li>
<?php endif; ?>

<?php if (isset($this->previous)): ?>
				<li>
					<a href="<?php echo $this->url(array('page' => $this->previous)); ?>"><i class="icon-backward" title="Previous"></i></a>
				</li>
<?php else: ?>
				<li class="disabled">
					<a href=""><i class="icon-backward" title="Previous"></i></a>
				</li>
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
				<li>
					<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
				</li>
	<?php else: ?>
				<li class="active">
					<a href="" title="Displaying Page <?php echo $this->current; ?> of <?php echo $this->last; ?>"><?php echo $page; ?></a>
				</li>
	<?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)): ?>
				<li>
					<a href="<?php echo $this->url(array('page' => $this->next)); ?>"><i class="icon-forward" title="Next"></i></a>
				</li>
<?php else: ?>
				<li class="disabled">
					<a href=""><i class="icon-forward" title="Next"></i></a>
				</li>
<?php endif; ?>

<?php if (isset($this->next)): ?>
				<li>
					<a href="<?php echo $this->url(array('page' => $this->last)); ?>"><i class="icon-fast-forward" title="Last"></i></a>
				</li>
<?php else: ?>
				<li class="disabled">
					<a href=""><i class="icon-fast-forward" title="Last"></i></a>
				</li>
<?php endif; ?>

			</ul>
		</div>
	</div>

</div>