<input id="iReloadPagination" type="button" name="reload" value="Refresh" class="cButton" />
<table id="iPaginate" class="cCommonTable" width="100%">
	<thead>
		<tr class="cHead">
			<td class="pagination_sort_head" order="ASC">Col 1</td>
			<td class="pagination_sort_head">Col 2</td>
			<td class="pagination_sort_head">Col 3</td>
		</tr>
		<tr class="cFilters">
			<td><input type="text" name="asdas" column="id" function="="/></td>
			<td><input type="text" name="asdas2" column="email" /></td>
			<td><input type="text" name="asdas3" column="username" /></td>
		</tr>
		<tr>
			<td colspan="3" class="cPages"></td>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="3" class="cPages"></td>
		</tr>
	</tfoot>
	<tbody>
		
	</tbody>
</table>