<?php echo $this->doctype() ?>
<html lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
<?php
	$aPartial = array('partials/navigation.phtml', 'kwgldev');
	$this->navigation()->menu()->setPartial($aPartial);
?>
		<div class="container" id="iDivNavigationContainer">
			<div class="row">
				<div class="span12 navbar navbar-inverse"><?php echo $this->navigation()->menu()->render(); ?></div>
			</div>
		</div>

		<div class="container" id="iDivBodyContainer">
			<div class="row">
				<div class="span12"><?php echo $this->layout()->content; ?></div>
			</div>
		</div>
	</body>
</html>