
<div id="iTabs">
	<ul>
		<li><a href="#ajax">Ajax Example</a></li>
		<li><a href="#pagination">Pagination Example</a></li>
		<li><a href="#ajaxForm">Ajax Form Submit Example</a></li>
	</ul>
	
	<div id="ajax">
		<?php echo $this->partial('js/examples/ajax.phtml') ?>
	</div>

	<div id="pagination">
		<?php echo $this->partial('js/examples/pagination.phtml') ?>
	</div>
	
	<div id="ajaxForm">
		<?php echo $this->form ?>
	</div>
</div>