<?php
$aContent = $this->aContent;

$aQuestionDetail = $aContent['question_detail'];
$aQuestionListing = $aContent['question_listing'];
$oFormRegister = $aContent['form_register'];
$iQuestionCount = $aContent['question_count'];
$iFirstQuestionPercentage = (100 / $iQuestionCount) * 1;
?>

<script>
	oQuestions = <?php echo json_encode($aQuestionListing); ?> ;

</script>
<!-- Home -->
<div id="iDivHome" class="panel" selected="true" scrolling="no">
	<h1 class="cH1HomeTitle">Randstad goudmeter<br>de topsporter in jou</h1>
	<p class="cPHomeDescription">
		Randstad begeleidt mensen in hun carrière. Zeker mensen die
		het beste uit zichzelf willen halen. Op welk niveau dan ook. Wil
		je weten waar jij staat in je carrière? De Randstad Goudmeter
		geeft je inzicht in je eigen kwaliteiten en ontwikkeling. Je
		resultaten kun je daarna meteen vergelijken met die van onze
		olympische topsporters.
	</p>
<!--	<p class="cPHomeDescription">
		Met het programma Goud op de Werkvloer
		begeleiden we topsporters die tijdens of na hun sportcarrière op zoek zijn naar een passende baan.
	</p>
	<p class="cPHomeDescription">Als voorbeeld van deze dienstverlening heeft
		Randstad een test ontwikkeld om je meer inzicht
		te geven in je eigen kwaliteiten en tegelijkertijd
		de kwaliteiten van Topsporters.
	</p>-->
	<a id="iADoTheTest" href="#iDivIntro">Naar de test</a>
</div>
<!-- End Home -->

<!-- Intro -->
<div id="iDivIntro" class="panel" scrolling="no">
	<h1 class="cH1IntroTitle">hoeveel karaats ben jij?</h1>
	<p class="cPIntroDescription cPHighlight">algemene toelichting</p>
	<p class="cPIntroDescription">
		Je gaat nu de Randstad Goudmeter invullen. Deze bestaat uit 48
		vragen en kost ongeveer 10 minuten van je tijd.
	</p>
	<p class="cPIntroDescription">
		De Randstad Goudmeter meet hoe jij
		activiteiten op je werk aanpakt. Daarna kun je
		zien hoe topsporters op deze punten scoren.
		Ben jij medaillemateriaal, of moet je nog
		verder werken aan je talentontwikkeling?
	</p>
	<img id="iImgChart" src="/img/default/chart.png"/>
<!--	<p class="cPIntroDescription cPHighlight">uitleg scores</p>-->
	<p class="cPIntroDescription">
		De scores worden uiteindelijk in een rapportage getoond.
		Deze rapportage kan je met een ervaren Randstad adviseur
		bespreken.
	</p>
	<a id="iAIntroMore" href="#iDivRegister">verder</a>
	<div class="cFooterBg"></div>
</div>
<!-- End Intro -->

<!-- Register -->
<div id="iDivRegister" class="panel cFooter" scrolling="no">
	<h1 class="cH1RegisterTitle">registreren</h1>
	<p class="cPRegisterDescription">
		Voor je de Randstad Goudmeter gaat invullen willen we graag
		nog een aantal zaken van je weten.
	</p>

	<!-- Registration Form -->

	<?php
	echo $oFormRegister;
	?>

</div>
<!-- End Register -->

<!-- Terms and Conditions -->
<div id="iDivTerms" class="panel" scrolling="no">
	<h1 class="cH1TermsTitle">Privacy verklaring</h1>
	<div id="iDivTermsWrapper">
		<div id="iDivTermsContainer">
	<p id="iPTermsDescription">
		<h1 class="cH1TermsSubTitle">Uw persoonsgegevens</h1>
		<p>In deze privacyverklaring wordt beschreven hoe PiCompany BV de door u verstrekte
persoonsgegevens verwerkt, opslaat en beveiligt. Onder persoonsgegevens verstaan wij alle
gegevens die specifiek herleidbaar zijn tot een persoon oftewel gegevens op basis waarvan
een persoon geïdentificeerd kan worden. Het gaat dan bijvoorbeeld om uw naam.
De verzameling, verwerking en opslag van uw gegevens vindt plaats in overeenstemming met
de Wet bescherming persoonsgegevens (Wbp) waaraan wij gebonden zijn volgens de
Nederlandse wet en de Europese Unie.<br>
Indien u een PiCompany test maakt op verzoek van een organisatie, dan houden wij ons -
binnen de door de Wbp gestelde grenzen - aan de nationale regelgeving die geldt voor deze
organisatie. In alle gevallen bewaakt PiCompany dat het beheer van uw gegevens op een
vertrouwelijke en ethische manier geschiedt.<br><br>
Met welk doel worden uw persoonsgegevens verzameld en verwerkt?<br>
PiCompany verzamelt en verwerkt uw persoons- en testgegevens om twee redenen:<br>
1. Om een rapportage te kunnen opleveren met daarin de resultaten van uw test.<br>
2. Voor onderzoek met als doel de kwaliteit van de tests/vragenlijsten te bewaken.<br>
PiCompany houdt zich daarbij aan de internationale richtlijnen die zijn opgesteld door de
EFPA (European Federation of Psychologists’ Associations). Er wordt bijvoorbeeld
onderzocht
of tests wel betrouwbaar, valide, eerlijk meten en er worden normgroepen samengesteld.
Voor onderzoek worden uw testgegevens altijd anoniem en op groepsniveau gerapporteerd;
deze zijn daardoor op geen enkele manier te herleiden tot u als persoon. Verstrekking van
extra
achtergrondgegevens ten behoeve van onderzoek is altijd vrijwillig. Of
u deze gegevens wel of niet verstrekt, heeft geen enkel gevolg voor uw resultaten of een
eventuele verdere procedure (bijvoorbeeld een sollicitatie). Uw antwoorden worden alleen
gebruikt voor onderzoek.
Uw gegevens worden niet langer bewaard dan nodig is voor het doel waarvoor deze
verzameld zijn.</p>
		<h1 class="cH1TermsSubTitle">Beveiliging en opslag van uw persoonsgegevens</h1>
<p>Door toepassing van technische en organisatorische maatregelen garandeert PiCompany een
passend beschermingsniveau van uw persoonsgegevens.
Wij maken gebruik van de laatste opslag- en beveiligingstechnieken om uw gegevens te
beschermen tegen toegang door onbevoegden en oneigenlijk gebruik. Uw gegevens kunnen
alleen gebruikt worden door de daarvoor geautoriseerde personen en alleen voor het doel
waarvoor uw gegevens oorspronkelijk verzameld zijn: het doel waar u eerder toestemming
voor verleend heeft.<br>
Medewerkers van PiCompany hebben alleen toegang tot uw persoonsgegevens wanneer dit
nodig is voor de eerder genoemde doeleinden (de inzet van rapportages of voor onderzoek)
en zijn verplicht om uw persoonsgegevens vertrouwelijk te behandelen conform de bepalingen
van de Wet bescherming persoonsgegevens, de internationale richtlijnen van de EFPA, en de
verder voor hun professie geldende beroepscodes.<br>
Rapportages over individuen worden alleen verstrekt aan personen die door PiCompany
gecertificeerd zijn met betrekking tot het goed kunnen interpreteren daarvan. Onderdeel
van
deze certificatie is dat de gecertificeerde personen toegerust zijn om het eerste
aanspreekpunt te zijn met betrekking tot verzamelen, bewaren, bewerken en interpreteren
van
individuele gegevens.<br>
Persoonsgegevens worden nooit zonder uw uitdrukkelijke toestemming overgedragen aan
derden.</p>
<h1 class="cH1TermsSubTitle">Uw rechten</h1>
<p>U hebt het recht een verzoek in te dienen voor het inzien van of verwijderen van
persoonsgegevens. Verzoeken kunnen bij voorkeur per e-mail, maar ook schriftelijk, worden
ingediend, waarbij bewijs van uw identiteit vereist is.<br>
E-mail: privacy@picompany.nl<br>
Postadres : PiCompany<br>
Postbus 2182<br>
3500 GD UTRECHT<br>
Nederland<br>
NB: Verzoeken kunnen niet telefonisch worden gedaan. Afhankelijk van het verzoek kan een
wettelijk vastgestelde administratievergoeding in rekening worden gebracht.
U ontvangt van ons binnen 4 weken antwoord.<br>
Voor alle verzoeken geldt:<br>
- U dient een (gescande) kopie van een identiteitsbewijs bij te voegen (paspoort,
rijbewijs,
identiteitskaart).<br>
- Het (gescande) verzoek dient door u gedateerd en ondertekend te zijn.
Een verzoek om verwijdering of aanpassing van persoonsgegevens, zal door PiCompany
altijd worden ingewilligd tenzij uw persoonsgegevens om administratieve of wettelijke
redenen
door ons bewaard moeten worden.<br>
Klachten over de verzameling en verwerking van uw gegevens via het PiCompany online
testsysteem, kunt u op dezelfde wijze bij PiCompany indienen.<br>
Voor het verzamelen, bewaren en rapporteren over individuele gegevens onder de regie van
een door PiCompany gecertificeerde persoon, geldt de klachtenregeling binnen de
betreffende organisatie waar deze persoon werkt.
	</p>
	</div>
	</div>
	<span id="iSpanBack" >terug</span>
	<div class="cFooterBg"></div>
</div>
<!-- End Terms and Conditions -->

<!-- How To -->
<div id="iDivHowTo" class="panel cFooter" scrolling="no">
	<h1 class="cH1HowtoTitle">hoe werkt het?</h1>
	<p class="cPHowtoDescription cPHighlight">uitleg</p>
	<p class="cPHowtoDescription">
		Je beantwoordt een vraag door het juiste antwoord naar het
vakje voor de vraag te slepen. Lees elke vraag zorgvuldig en
bedenk in hoeverre je het gedrag laat zien in een werksituatie.
Vul in wie je feitelijk bent, niet wie je zou willen zijn. Je eerste
antwoord dat je te binnen schiet sluit meestal het beste aan.
Neem dan ook niet te veel tijd om de antwoorden tegen elkaar
af te wegen. Nadat je alle vragen hebt ingevuld ontvang je een
rapportage. Hieronder staat een voorbeeld vraag.
	</p>
	<!--	<div id="iDivImageHowTo"></div>-->
	<!--Actual drag and drop demo-->
	<div id="iDivDragDropDemoContainer">
		<div id="iDivImageArrow"></div>
		<div class="question">
			<div class="cDivAnswreholder"></div>
			<span class="cSpanQuestionNumber">vraag 1</span>
			<h1 class="cH1Question">Ik plan zorgvuldig op welke manier ik iets ga aanpakken.</h1>
		</div>
		<div class="cDivAnswerList">
			<div class="cDivAnswerNo" style="background-color: #00308f;"><span class="cTextFormat">Bijna nooit</span></div>
			<div id="iDivAnswerLittle" class="cDivAnswerLittle" style="background-color: #e2008a;"><span class="cTextFormat">Soms</span></div>
			<div class="cDivAnswerSometimes" style="background-color: #b8d000;"><span class="cTextFormat">Regelmatig</span></div>
			<div class="cDivAnswerOften" style="background-color: #f49100;"><span class="cTextFormat">Vaak</span></div>
			<div class="cDivAnswerYes" style="background-color: #2175d9;"><span class="cTextFormat">Bijna altijd</span></div>
		</div>
	</div>
	<!--End Actual drag and drop demo-->
	<a id="iAStartTheTest" href="#iDivTest1">Start de test</a>
</div>
<!-- End How To -->

<!-- Questions -->
<span id="iSpanParticipantId">1</span>
<span id="iSpanQuestionCount"><?php echo $iQuestionCount; ?></span>
<div id="iDivTest1" class="panel cFooter" data-unload="resetQuestion" scrolling="no">
	<h1 class="cH1HowtoTitle"></h1>
	<div class="cDivProgressbar"><div class="cDivMarker" style="width: <?php echo $iFirstQuestionPercentage . '%'; ?>;"></div></div>
	<div class="question">
		<h1 class="cH1QuestionTitle">in hoeverre is deze uitspraak van toepassing op je gedrag in je werk</h1>
		<div class="cDivAnswreholder"></div>
		<span id="iSpanQuestionNumber1" class="cSpanQuestionNumber">vraag 1</span>
		<h1 id="iH1Question<?php echo $aQuestionDetail['id']; ?>" class="cH1Question"><?php echo $aQuestionDetail['question']; ?></h1>
	</div>

	<div class="cDivAnswerList">
		<div class="cDivAnswerNo" style="background-color: #00308f;"><span id="iSpanAnswer1No" class="cTextFormat">Bijna nooit</span></div>
		<div class="cDivAnswerLittle" style="background-color: #e2008a;"><span id="iSpanAnswer1Little" class="cTextFormat">Soms</span></div>
		<div class="cDivAnswerSometimes" style="background-color: #b8d000;"><span id="iSpanAnswer1Sometimes" class="cTextFormat">Regelmatig</span></div>
		<div class="cDivAnswerOften" style="background-color: #f49100;"><span id="iSpanAnswer1Often" class="cTextFormat">Vaak</span></div>
		<div class="cDivAnswerYes" style="background-color: #2175d9;"><span id="iSpanAnswer1Yes" class="cTextFormat">Bijna altijd</span></div>
	</div>

	<span id="iSpanButtonNext1" class="cSpanNext" >volgende</span>
</div>

<div id="iDivTest2" class="panel cFooter" data-unload="resetQuestion" scrolling="no">
	<h1 class="cH1HowtoTitle"></h1>
	<div class="cDivProgressbar"><div class="cDivMarker"></div></div>
	<div class="question">
		<h1 class="cH1QuestionTitle">in hoeverre is deze uitspraak van toepassing op je gedag in je werk</h1>
		<div class="cDivAnswreholder"></div>
		<span id="iSpanQuestionNumber2" class="cSpanQuestionNumber">Vraag 1</span>
		<h1 id="iH1Question2" class="cH1Question"></h1>
	</div>

	<div class="cDivAnswerList">
		<div class="cDivAnswerNo" style="background-color: #00308f;"><span id="iSpanAnswer2No" class="cTextFormat">Bijna nooit</span></div>
		<div class="cDivAnswerLittle" style="background-color: #e2008a;"><span id="iSpanAnswer2Little" class="cTextFormat">Soms</span></div>
		<div class="cDivAnswerSometimes" style="background-color: #b8d000;"><span id="iSpanAnswer2Sometimes" class="cTextFormat">Regelmatig</span></div>
		<div class="cDivAnswerOften" style="background-color: #f49100;"><span id="iSpanAnswer2Often" class="cTextFormat">Vaak</span></div>
		<div class="cDivAnswerYes" style="background-color: #2175d9;"><span id="iSpanAnswer2Yes" class="cTextFormat">Bijna altijd</span></div>
	</div>

	<span id="iSpanButtonNext2" class="cSpanNext" >volgende</span>
</div>
<!-- End Questions -->

<!-- Finish -->
<div id="iDivFinish" class="panel cFooter" scrolling="no">
	<h1 class="cH1HowtoTitle"></h1>
	<div class="cDivProgressbar"><div class="cDivMarker"></div></div>
	<h1 class="cPFinishTitle">Bedankt</h1>
<!--	<p class="cPFinishDescription cPHighlight">rapport</p>-->
	<p class="cPFinishDescription">
		Van je resultaten wordt nu een rapport gemaakt. Dit wordt persoonlijk aan je overhandigd. 
        Het rapport geeft je scores weer op de dimensies doelen stellen, doelen bewaken, prestaties beoordelen, prestaties verbeteren, inspanning leveren en vertrouwen tonen. 
        Meer uitleg over deze dimensies vind je in het rapport. Je kunt je scores ook bespreken met een ervaren Randstad consultant in het Holland Heineken House.
	</p>
    <p class="cPFinishDescription">Werken aan sportieve ambities</p>
	<p class="cPFinishDescription">
		Randstad heeft een overtuiging: wij geloven in de groei van mens en organisatie. Daar werken we iedere dag aan. 
        We begeleiden mensen in hun carrière, helpen ze het beste uit zichzelf te halen. Sporters zijn daar iedere dag mee bezig. 
        Vanwege hun sportieve drive, passie en ambitie voelen we ons met hen verbonden. 
        Daarom steunen wij als Partner in Sport van NOC*NSF sporters met onze diensten, 
        we helpen ze hun sportieve en maatschappelijke ambities waar te maken. 
        Meer weten over wat Randstad voor jouw ambities kan betekenen? Kijk op http://www.randstad.nl
		<!--		<a href="www.randstad.nl">www.randstad.nl.</a>-->
	</p>
<!--	<p class="cPFinishDescription cPHighlightRed">En nog ruimte voor Randstad om iets te zeggen over hun dienstverlening e.d. </p>-->
	<a id="iAClose" href="#iDivHome">Afsluiten</a>
</div>
<!-- End Finish -->