<div class="row">
    

  <!-- Wrapper for slides -->
  <ul class="bxslider">
    <li id="iDivIntro" class="col-sm-12">
        <div class="row">
            <div class="col-sm-12">
                  <h1 class="text-primary">inschrijven bij Randstad</h1>

                          uitleg bij deze pagina
              Met dit formulier schrijf je je in bij Randstad, en maak je gelijk je persoonlijke Mijn Randstad-
              account aan. Met je Mijn Randstad-account kun je net zo vaak solliciteren als je wilt.
              Door gebruik te maken van de invoerhulp ‘Ik gebruik mijn gegevens uit mijn cv’, worden de meeste gegevens uit je cv meteen ingeladen. Dus schrijf je in en vind nu nog sneller de baan die bij je past!
              Heb je al een account en wil je je gegevens wijzigen, log dan in met je Mijn Randstad-account. Daarna kun je je gegevens aanpassen.

              <h2 class="text-primary">inschrijfformulier</h2>
              Om het inschrijven makkelijker te maken, kies je eerst de manier waarop je je gegevens in het formulier wilt invullen. Dit kan bijvoorbeeld via LinkedIn of je Mijn Randstad-account.
              <br /><br />
              * Hoe ga je je gegevens invullen?<br /><br />
              <div class="well" id="iDivFillChoice">
                    <button type="button" class="btn btn-primary btn-lg btn-block">
                      Ik gebruik mijn gegevens uit LinkedIn
                    </button>
                    <button type="button" rel="iDivFormManual" class="btn btn-primary btn-lg btn-block">
                      Ik vul het sollicitatieformulier zelf in
                    </button>
              </div>    
                  <br /><br />
          </div>
          </div>
    </li>
    <li id="iDivFormManual" class="col-sm-12">
            <form class="form-horizontal" role="form">
            
            <div class="row">
              <div class="col-sm-12">
                <h2>vul je gegevens in</h2>
Je gegevens worden vertrouwelijk behandeld.
              </div>
              </div>
            <div class="form-group">
              <label for="inputRoepnaam" class="col-lg-2 col-sm-2 control-label">Roepnaam</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputRoepnaam" placeholder="Roepnaam">
              </div>
            </div>
            <div class="form-group">
              <label for="inputVoorletters" class="col-lg-2 col-sm-2 control-label">Voorletters</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputVoorletters" placeholder="Voorletters">
              </div>
            </div>
            <div class="form-group">
              <label for="inputTussenvoegsel" class="col-lg-2 col-sm-2 control-label">Tussenvoegsel</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputTussenvoegsel" placeholder="Tussenvoegsel">
              </div>
            </div>
            <div class="form-group">
              <label for="inputAchternaam" class="col-lg-2 col-sm-2 control-label">Achternaam</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputAchternaam" placeholder="Achternaam">
              </div>
            </div>
            <div class="form-group">
              <label for="inputGeboortedatum" class="col-lg-2 col-sm-2 control-label">Geboortedatum</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputGeboortedatum" placeholder="Geboortedatum">
              </div>
            </div>
            <div class="form-group">
              
            </div>
            <div class="form-group">
              <label class="col-lg-2 col-sm-2 control-label">geslacht</label>
              <div class="col-lg-10 col-sm-10">
                  <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsGeslacht" id="optionsGeslacht1" value="option1">
                      man
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsGeslacht" id="optionsGeslacht2" value="option2">
                      vrouw
                    </label>
                    
                  </div>
                
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 col-sm-2 control-label">burgerlijke staat</label>
              <div class="col-lg-10 col-sm-10">
                  <div class="btn-group btn-group-justified" data-toggle="buttons">
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsBurg" id="optionsBurg1" value="option1">
                      duurzaam gescheiden
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsBurg" id="optionsBurg2" value="option2">
                      gehuwd
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsBurg" id="optionsBurg3" value="option3">
                      ongehuwd
                    </label>
                    
                  </div>
                
              </div>
            </div>
<div class="form-group">
              <label for="inputStraat" class="col-lg-2 col-sm-2 control-label">Straat</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputStraat" placeholder="Straat">
              </div>
            </div>
            <div class="form-group">
              <label for="inputHuisnummer" class="col-lg-2 col-sm-2 control-label">Huisnummer</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputHuisnummer" placeholder="Huisnummer">
              </div>
            </div>
            <div class="form-group">
              <label for="inputToevoeging" class="col-lg-2 col-sm-2 control-label">Toevoeging</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputToevoeging" placeholder="Toevoeging">
              </div>
            </div>
            <div class="form-group">
              <label for="inputPostcode" class="col-lg-2 col-sm-2 control-label">Postcode</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputPostcode" placeholder="Postcode">
              </div>
            </div>
            <div class="form-group">
              <label for="inputWoonplaats" class="col-lg-2 col-sm-2 control-label">Woonplaats</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputWoonplaats" placeholder="Woonplaats">
              </div>
            </div>
            <div class="form-group">
              <label for="land" class="col-lg-2 col-sm-2 control-label">Land</label>
              <div class="col-lg-10 col-sm-10">
                  <select class="form-control" id="land">
                  <option>Nederland</option>
                  <option>Duitsland</option>
                  <option>Belgie</option>
                  <option>Engeland</option>
                  <option>Frankrijk</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="inputTelefoonnummer" class="col-lg-2 col-sm-2 control-label">Telefoonnummer</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputTelefoonnummer" placeholder="Telefoonnummer">
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail" class="col-lg-2 col-sm-2 control-label">e-mailadres</label>
              <div class="col-lg-10 col-sm-10">
                <input type="email" class="form-control" id="inputEmail" placeholder="e-mailadres">
              </div>
            </div>
            <div class="form-group">
              
            </div>
            <div class="form-group">
              <label class="col-lg-2 col-sm-2 control-label">Rijbewijs</label>
              <div class="col-lg-10 col-sm-10">
                  <div class="btn-group btn-group-justified" data-toggle="buttons">
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar1" value="option1">
                      A
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar2" value="option2">
                      B
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar3" value="option3">
                      BE
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar4" value="option4">
                      C
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar5" value="option5">
                      CE
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar6" value="option6">
                      D
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar7" value="option7">
                      DE
                    </label>
                    <label class="btn btn-primary">
                      <input type="radio" name="optionsCar" id="optionsCar8" value="option8">
                      geen
                    </label>
                    
                  </div>
                
              </div>
              
              
              
            </div>
            <div class="row">
              <div class="col-sm-12">
            <h2>Hoogst afgeronde opleiding</h2>
              </div>
              </div>
            <div class="form-group">
              <label for="inputOpleiding" class="col-lg-2 col-sm-2 control-label">Opleiding</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputOpleiding" placeholder="Opleiding">
              </div>
            </div>
            <div class="form-group">
              <label for="inputDiploma" class="col-lg-2 col-sm-2 control-label">Diploma behaald</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputDiploma" placeholder="Diploma">
              </div>
            </div>
            <div class="form-group">
              <label for="inputNiveau" class="col-lg-2 col-sm-2 control-label">Werk- en denkniveau</label>
              <div class="col-lg-10 col-sm-10">
                <select class="form-control" id="niveau">
                  <option>WO</option>
                  <option>HBO</option>
                  <option>MBO</option>
                  <option>VBO</option>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
            <h2>Laatste werkervaring</h2>
              </div>
              </div>
            <div class="form-group">
              <label for="inputFunctie" class="col-lg-2 col-sm-2 control-label">Functie</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputFunctie" placeholder="Functie">
              </div>
            </div>
            <div class="form-group">
              <label for="inputWerkgever" class="col-lg-2 col-sm-2 control-label">Werkgever</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputWerkgever" placeholder="Werkgever">
              </div>
            </div>
            <div class="form-group">
              <label for="inputToevoeging" class="col-lg-2 col-sm-2 control-label">Verwachte einddatum</label>
              <div class="col-lg-10 col-sm-10">
                    <input type="date" class="form-control" placeholder="Datum">
                    
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
            <h2>voorkeuren</h2>
Vanaf wanneer ben je beschikbaar? Hier geef je je beschikbaarheid op. 
Dit wordt gebruikt om in de toekomst banen te zoeken die bij je passen.
Via Mijn Randstad kun je je beschikbaarheid onderhouden.
              </div>
              </div>
            <div class="form-group">
              <label for="inputVan" class="col-lg-2 col-sm-2 control-label">Van</label>
              <div class="col-lg-4 col-sm-4">
                    <input type="date" class="form-control" placeholder="Datum">
                    
              </div>
              <label for="inputTot" class="col-lg-2 col-sm-2 control-label">Tot</label>
              
              <div class="col-lg-4 col-sm-4">
                    <input type="date" class="form-control" placeholder="Datum">
                    
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
Geef hier je algemene voorkeuren aan. Deze informatie kan gebruikt worden 
voor het voorstellen voor andere vacatures.
              </div>
              </div>
            <div class="form-group">
              <label for="inputFunctie" class="col-lg-2 col-sm-2 control-label">Uren per week</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputFunctie" placeholder="Functie">
              </div>
            </div>
            <div class="form-group">
              <label for="inputWerkgever" class="col-lg-2 col-sm-2 control-label">Dagen per week</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputWerkgever" placeholder="Werkgever">
              </div>
            </div>
            <div class="form-group">
              <label for="inputWerkgever" class="col-lg-2 col-sm-2 control-label">Maximale enkele reis</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputWerkgever" placeholder="Werkgever">
              </div>
            </div>
            <div class="form-group">
              <label for="inputWerkgever" class="col-lg-2 col-sm-2 control-label">Gewenst bruto salaris</label>
              <div class="col-lg-10 col-sm-10">
                <input type="text" class="form-control" id="inputWerkgever" placeholder="Werkgever">
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12 col-sm-12">
                <div class="checkbox">
                  <label>
                    <input type="checkbox" value="">
                    Option one is this and that&mdash;be sure to include why it's great
                  </label>
                </div>
              </div>
            </div>
            
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10 col-sm-10">
                <button type="submit" class="btn btn-primary">Sign in</button>
              </div>
            </div>
          </form>
    </li>
  </ul>

    
</div>


<script type="text/javascript">
    $(document).ready(function(){
        var slides = [];
        $('.bxslider li').each(function(i){
            slides[$(this).attr('id')]=i;
        });
        slider = $('.bxslider').bxSlider({
            adaptiveHeight: true,
            speed:300,
            slideMargin:30,
            touchEnabled:false,
            pager:false
          });
            
          $('#iDivFillChoice button').click(function(){
              var slideID = $(this).attr('rel');
              if($('#'+slideID).length){
              document.location.href = '#'+slideID;
                slider.goToSlide(slides[slideID]);
              }
          });
});
    </script>