sample.phtml - You are at default / index / sample

<div class="cContainer-12">
	<div class="cGrid-12 cFullWidth">Full width</div>
	<div class="cGrid-01 cVeryThin1">1</div>
	<div class="cGrid-02 cVeryThin2">2</div>
	<div class="cGrid-03 cVeryThin3">3</div>
	<div class="cGrid-06 cLast cNotSoThin6">6</div>
	<div class="cGrid-04 cNotSoThin4">4</div>
	<div class="cGrid-04 cNotSoThin4">4</div>
	<div class="cGrid-04 cLast cNotSoThin4">4</div>
	<div class="cGrid-05 cNotSoThin5">5</div>
	<div class="cGrid-05 cNotSoThin5">5</div>
	<div class="cGrid-02 cLast cVeryThin2">2</div>
	<div class="cGrid-07 cSortaFat7">7</div>
	<div class="cGrid-05 cLast cNotSoThin5">5</div>
	<div class="cGrid-08 cSortaFat8">8</div>
	<div class="cGrid-04 cLast cNotSoThin4">4</div>
	<div class="cGrid-09 cSortaFat9">9</div>
	<div class="cGrid-03 cLast cVeryThin3">3</div>
	<div class="cGrid-10 cFatso10">10</div>
	<div class="cGrid-02 cLast cVeryThin2">2</div>
	<div class="cGrid-11 cFatso11">11</div>
	<div class="cGrid-01 cLast cVeryThin1">1</div>
	<div class="cGrid-12 cFullWidth">Full width</div>
</div>
<br class="cClearFix" />
<div class="cContainer-16">
	<div class="cGrid-16 cFullWidth">Full width</div>
	<div class="cGrid-01 cVeryThin1">1</div>
	<div class="cGrid-15 cLast cHugeso15">15</div>
	<div class="cGrid-02 cVeryThin2">2</div>
	<div class="cGrid-14 cLast cHugeso14">14</div>
	<div class="cGrid-03 cVeryThin3">3</div>
	<div class="cGrid-13 cLast cHugeso13">13</div>
	<div class="cGrid-04 cNotSoThin4">4</div>
	<div class="cGrid-12 cLast cHugeso12">12</div>
	<div class="cGrid-05 cNotSoThin5">5</div>
	<div class="cGrid-11 cLast cFatso11">11</div>
	<div class="cGrid-06 cNotSoThin6">6</div>
	<div class="cGrid-10 cLast cFatso10">10</div>
	<div class="cGrid-07 cSortaFat7">7</div>
	<div class="cGrid-09 cLast cSortaFat9">9</div>
	<div class="cGrid-08 cSortaFat8">8</div>
	<div class="cGrid-08 cLast cSortaFat8">8</div>
</div>