<?php echo $this->doctype() ?>
<html lang="nl">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle('Randstad Topsporter') ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
		<div id="iDivWrapper">
			<div id="jQUi">
				<div id="content">
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
		</div>
	</body>
	<div id="iDivDropSound" ><audio id="dropSound" src="/audio/default/drop.mp3" preload="auto"></audio></div>
</html>