<div class="navbar-inner">

	<div class="container">

		<a class="brand" href="/kwgldev/">KWGL Dev</a>
		<ul class="nav">
			<li class="divider-vertical"></li>
<?php
foreach ($this->container as $oPage) {

	if (empty($oPage->pages)) {
		$bDropdown = false;
?>
			<li class="<?php if ($oPage->isActive()) { ?> active<?php } ?>">
				<a href="<?php echo $oPage->getHref(); ?>"><?php echo $oPage->getLabel(); ?></a>
<?php
	} else {
		$bDropdown = true;
?>
			<li class="dropdown<?php if ($oPage->isActive()) { ?> active<?php } ?>">
	<?php if ($oPage->getLabel() == 'my-account') {	?>
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-white icon-user"></i><b class="caret"></b></a>
	<?php } else { ?>
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $oPage->getLabel(); ?><b class="caret"></b></a>
	<?php } ?>
<?php
	}

	if ($bDropdown) {
?>
				<ul class="dropdown-menu">
<?php
		foreach ($oPage->pages as $oSubPage) {
?>
			<li class="<?php if ($oSubPage->isActive()) { ?> active<?php } ?>">
				<a href="<?php echo $oSubPage->getHref(); ?>"><?php echo $oSubPage->getLabel(); ?></a>
			</li>
<?php
		}
?>
				</ul>
<?php
	}
?>
			</li>
<?php
}
?>
		</ul>
	</div>
</div>