<div class="cDivZendFormWrapper">
	<form <?php echo $this->formAttributes($this); ?>>
		<table>
			<tbody>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textName->getId()); ?>">
							<?php echo $this->element->textName->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textName; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textAge->getId()); ?>">
							<?php echo $this->element->textAge->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textAge; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textEmail->getId()); ?>">
							<?php echo $this->element->textEmail->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textEmail; ?>
						</div>
					</td>
				</tr>
<?php /*				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textFirstName->getId()); ?>">
							<?php echo $this->element->textFirstName->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textFirstName; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textLastName->getId()); ?>">
							<?php echo $this->element->textLastName->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textLastName; ?>
						</div>
					</td>
				</tr>	*/	?>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->radioGender->getId()); ?>">
							<?php echo $this->element->radioGender->getLabel(); ?>
						</label>
					</td>
					<td>
						<div id="iDiv<?php echo ucfirst($this->element->radioGender->getId()); ?>" class="cDivElement">
							<?php echo $this->element->radioGender; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->selectHighestTraining->getId()); ?>">
							<?php echo $this->element->selectHighestTraining->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->selectHighestTraining; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->selectLastTraining->getId()); ?>">
							<?php echo $this->element->selectLastTraining->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->selectLastTraining; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->selectJobCategory->getId()); ?>">
							<?php echo $this->element->selectJobCategory->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->selectJobCategory; ?>
						</div>
					</td>
				</tr>
<?php /*				<tr>
					<td>geboortedatum</td>
					<td>
						<?php echo $this->element->selectDate; ?>
						<?php echo $this->element->selectMonth; ?>
						<?php echo $this->element->selectYear; ?>
					</td>
				</tr>	*/ ?>
<?php /*				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textAge->getId()); ?>">
							<?php echo $this->element->textAge->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textAge; ?>
						</div>
					</td>
				</tr>	*/	?>
<?php /*				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textEmail->getId()); ?>">
							<?php echo $this->element->textEmail->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textEmail; ?>
						</div>
					</td>
				</tr>	*/	?>
<?php /*				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textEducation->getId()); ?>">
							<?php echo $this->element->textEducation->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textEducation; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textTrainingType->getId()); ?>">
							<?php echo $this->element->textTrainingType->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textTrainingType; ?>
						</div>
					</td>
				</tr>	*/	?>
<?php /*				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textCareerLevel->getId()); ?>">
							<?php echo $this->element->textCareerLevel->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textCareerLevel; ?>
						</div>
					</td>
				</tr>	*/	?>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textYearsOfExperience->getId()); ?>">
							<?php echo $this->element->textYearsOfExperience->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textYearsOfExperience; ?>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->radioLeading->getId()); ?>">
							<?php echo $this->element->radioLeading->getLabel(); ?>
						</label>
					</td>
					<td>
						<div id="iDiv<?php echo ucfirst($this->element->radioLeading->getId()); ?>" class="cDivElement">
							<?php echo $this->element->radioLeading; ?>
						</div>
					</td>
				</tr>
				<tr id="iTrNumberOfEmployees" class="cVisibilityHidden">
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textNumberOfEmployees->getId()); ?>">
							<?php echo $this->element->textNumberOfEmployees->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textNumberOfEmployees; ?>
						</div>
					</td>
				</tr>
<?php /*				<tr>
					<td>
						<label id="iLabel<?php echo ucfirst($this->element->textFieldOfInterest->getId()); ?>">
							<?php echo $this->element->textFieldOfInterest->getLabel(); ?>
						</label>
					</td>
					<td>
						<div class="cDivElement">
							<?php echo $this->element->textFieldOfInterest; ?>
						</div>
					</td>
				</tr>	*/ ?>
				<tr>
					<td>&nbsp;</td>
					<td>
						<?php echo $this->element->checkAgree; ?>&nbsp;
						<label for="<?php echo $this->element->checkAgree->getId(); ?>" id="iLabel<?php echo ucfirst($this->element->checkAgree->getId()); ?>">
							<?php echo $this->element->checkAgree->getLabel(); ?>
						</label>
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td><?php echo $this->element->submitSubmit; ?></td>
				</tr>
		<?php
			/*foreach($this->element as $oElement) {	?>
				<tr>
		<?php	if ($oElement instanceof Zend_Form_Element_Hash) {
					// Ignore CSRF Hash Element as it is handled by the csrfHash View Helper above
					continue;
				}
				if ($oElement instanceof Zend_Form_Element_Submit) {
					?>
					<td>&nbsp;</td>
					<td><?php echo $oElement; ?></td>
					<?php
				}
				elseif ($oElement instanceof Zend_Form_Element_Hash || $oElement instanceof Zend_Form_Element_Hidden) {
					echo $oElement;
				}
				elseif ($oElement instanceof Zend_Form_Element_Checkbox) {	?>
					<td>&nbsp;</td>
					<td>
						<?php echo $oElement; ?>&nbsp;
						<label for="<?php echo $oElement->getId(); ?>" id="iLabel<?php echo ucfirst($oElement->getId()); ?>"><?php echo $oElement->getLabel(); ?></label>
					</td>
					<?php
				}
				else {
					?>
						<td><label id="iLabel<?php echo ucfirst($oElement->getId()); ?>"><?php echo $oElement->getLabel(); ?></label></td>
						<td><div class="cDivElement"><?php echo $oElement; ?></div></td>
					<?php
				}	?>
				</tr>
	<?php	}	*/?>
			</tbody>
		</table>
	</form>
</div>