<script id="iTemplateBasePagination" type="text/x-jsrender">
<div class="row">

	<div class="span3 cDivPaginationPageOfPage">Page {{:current}} of {{:pageCount}}</div>

	<div class="span9">
		<div class="pagination pagination-right">
			<ul>

{{if previous}}
				<li title="First - Go to page {{:first}}">
					<a href="javascript:;" class="cPaginationPaginateLink" page_to_go_to="{{:first}}"><i class="icon-fast-backward"></i></a>
				</li>
				<li title="Previous - Go to page {{:previous}}">
					<a href="javascript:;" class="cPaginationPaginateLink" page_to_go_to="{{:previous}}"><i class="icon-backward"></i></a>
				</li>
{{else}}
				<li class="disabled">
					<a href="javascript:;"><i class="icon-fast-backward" title="First"></i></a>
				</li>
				<li class="disabled">
					<a href="javascript:;"><i class="icon-backward" title="Previous"></i></a>
				</li>
{{/if}}

{{pagination pagesInRange current pageCount}}
	{{if ~current == #data}}
				<li class="active" title="Page {{:#data}} of {{:~pageCount}}">
					<a href="javascript:;" class="cPaginationPaginateLink cPaginationPaginateLinkActive" page_to_go_to="{{:#data}}">{{:#data}}</a>
				</li>
	{{else}}
				<li title="Go to page {{:#data}}">
					<a href="javascript:;" class="cPaginationPaginateLink" page_to_go_to="{{:#data}}">{{:#data}}</a>
				</li>
	{{/if}}
{{/pagination}}

{{if next}}
				<li title="Next - Go to page {{:next}}">
					<a href="javascript:;" class="cPaginationPaginateLink" page_to_go_to="{{:next}}"><i class="icon-forward"></i></a>
				</li>
				<li title="Last - Go to page {{:last}}">
					<a href="javascript:;" class="cPaginationPaginateLink" page_to_go_to="{{:last}}"><i class="icon-fast-forward"></i></a>
				</li>
{{else}}
				<li class="disabled">
					<a href="javascript:;"><i class="icon-forward" title="Next"></i></a>
				</li>
				<li class="disabled">
					<a href="javascript:;"><i class="icon-fast-forward" title="Last"></i></a>
				</li>
{{/if}}

			</ul>
		</div>
	</div>

</div>
</script>